# Generated by Django 2.2.6 on 2022-06-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Supervisor', 'Supervisor'), ('Admin', 'Admin'), ('Moderator', 'Moderator')], default='Supervisor', max_length=32),
        ),
    ]
